#!/usr/bin/env -S npx tsx
// generate-music.ts — Generate all 17 music tracks for Athena Crisis via ElevenLabs.
// Run after the main audio generation completes (which generates hestias-serenade).

import { ElevenLabsClient } from '@elevenlabs/elevenlabs-js';
import { config } from 'dotenv';
import { createWriteStream, existsSync, mkdirSync } from 'fs';
import { stat } from 'fs/promises';
import { join, resolve } from 'path';
import { Readable } from 'stream';
import { pipeline } from 'stream/promises';

config({ path: '/workspace/gamemaker/.env' });

const CONCURRENCY = 2;
const outputDir = resolve(import.meta.dirname, 'music');

interface MusicTrack {
  name: string;
  prompt: string;
  durationMs: number;
  file: string;
}

const tracks: MusicTrack[] = [
  {
    name: 'apollos-ascend',
    prompt:
      'Looping instrumental music for desert adventure game. Warm middle-eastern strings, gentle percussion, ascending hopeful melody. Strategic and mysterious. ~110 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'apollos-ascend.mp3',
  },
  {
    name: 'apollos-gleam',
    prompt:
      'Looping instrumental music for desert strategy game. Shimmering golden synths, exotic flute, steady drums. Bright and tactical. ~100 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'apollos-gleam.mp3',
  },
  {
    name: 'ares-chaos',
    prompt:
      'Looping instrumental music for volcanic battlefield game. Intense heavy drums, aggressive brass, fiery strings. Chaotic and dangerous. ~130 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'ares-chaos.mp3',
  },
  {
    name: 'ares-skirmish',
    prompt:
      'Looping instrumental music for volcanic combat game. Driving percussion, tense strings, smoldering brass. Focused and combative. ~120 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'ares-skirmish.mp3',
  },
  {
    name: 'artemis-glade',
    prompt:
      'Looping instrumental music for peaceful forest strategy game. Gentle acoustic guitar, soft flute, nature-inspired. Calm and pastoral. ~90 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'artemis-glade.mp3',
  },
  {
    name: 'artemis-hunt',
    prompt:
      'Looping instrumental music for grassland battlefield strategy. Heroic strings, military snare, adventurous brass. Bold and tactical. ~115 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'artemis-hunt.mp3',
  },
  {
    name: 'astraeus-expanse',
    prompt:
      'Looping instrumental music for space station strategy game. Ambient electronic pads, futuristic synths, subtle pulse. Vast and sci-fi. ~95 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'astraeus-expanse.mp3',
  },
  {
    name: 'astraeus-wings',
    prompt:
      'Looping instrumental music for spaceship combat game. Electronic beats, soaring synth leads, cosmic atmosphere. Exciting and futuristic. ~110 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'astraeus-wings.mp3',
  },
  {
    name: 'chiones-cloud',
    prompt:
      'Looping instrumental music for snowy peaceful landscape game. Ethereal chimes, soft piano, gentle wind pads. Serene and cold. ~80 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'chiones-cloud.mp3',
  },
  {
    name: 'chiones-leap',
    prompt:
      'Looping instrumental music for snowy battlefield strategy. Crisp strings, military percussion, icy synths. Determined and wintry. ~105 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'chiones-leap.mp3',
  },
  {
    name: 'eos-dawn',
    prompt:
      'Looping instrumental music for epic dawn awakening in strategy game. Rising orchestral strings, triumphant horns, hopeful melody. Grand and inspiring. ~100 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'eos-dawn.mp3',
  },
  {
    name: 'gaias-rise',
    prompt:
      'Looping instrumental music for earth elemental strategy game. Deep bass drums, powerful brass, nature and stone sounds. Mighty and ancient. ~95 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'gaias-rise.mp3',
  },
  // hestias-serenade is generated by the main manifest
  {
    name: 'poseidons-tide',
    prompt:
      'Looping instrumental music for swamp marshland strategy game. Murky bass, tribal drums, mysterious woodwinds. Ominous and wet. ~90 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'poseidons-tide.mp3',
  },
  {
    name: 'poseidons-wrath',
    prompt:
      'Looping instrumental music for stormy swamp battle game. Crashing waves percussion, dark brass, thunderous drums. Furious and watery. ~120 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'poseidons-wrath.mp3',
  },
  {
    name: 'selenes-tranquility',
    prompt:
      'Looping instrumental music for lunar landscape strategy game. Dreamy synth pads, celestial bells, floating ambient. Peaceful and cosmic. ~75 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'selenes-tranquility.mp3',
  },
  {
    name: 'selenes-voyage',
    prompt:
      'Looping instrumental music for moon exploration strategy game. Mysterious electronic pulse, stellar arpeggios, wonder-filled. Adventurous and alien. ~100 BPM. Seamless loop.',
    durationMs: 30000,
    file: 'selenes-voyage.mp3',
  },
];

async function pooled<T>(
  items: T[],
  concurrency: number,
  fn: (item: T) => Promise<void>,
): Promise<void> {
  const queue = [...items];
  const workers = Array.from({ length: concurrency }, async () => {
    while (queue.length > 0) {
      const item = queue.shift()!;
      await fn(item);
    }
  });
  await Promise.all(workers);
}

async function main() {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  if (!apiKey) {
    console.error('ELEVENLABS_API_KEY required');
    process.exit(1);
  }

  mkdirSync(outputDir, { recursive: true });
  const client = new ElevenLabsClient({ apiKey });

  console.log(`Generating ${tracks.length} music tracks (concurrency: ${CONCURRENCY})...`);

  await pooled(tracks, CONCURRENCY, async (track) => {
    const outputPath = join(outputDir, track.file);
    if (existsSync(outputPath)) {
      const size = (await stat(outputPath)).size;
      if (size > 0) {
        console.log(`  ✓ ${track.name} (exists, ${(size / 1024).toFixed(0)} KB)`);
        return;
      }
    }

    try {
      console.log(`  ⏳ ${track.name}...`);
      const audio = await client.music.compose({
        prompt: track.prompt,
        musicLengthMs: track.durationMs,
        forceInstrumental: true,
        outputFormat: 'mp3_44100_128',
      });
      await pipeline(Readable.from(audio), createWriteStream(outputPath));
      const sizeMB = ((await stat(outputPath)).size / 1024 / 1024).toFixed(2);
      console.log(`  ✓ ${track.name} (${sizeMB} MB)`);
    } catch (err: any) {
      console.error(`  ✗ ${track.name}: ${err.message}`);
    }
  });

  console.log('\nDone!');
}

main().catch((err) => {
  console.error('Music generation failed:', err.message);
  process.exit(1);
});
